name: test
on:
  push:
    branches:
      - main
      - development
    paths:
      - 'packages/dev-team-bot/**'
      - '.github/workflows/dev-team-bot.yml'
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'packages/dev-team-bot/**'
      - '.github/workflows/dev-team-bot.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]
    env:
      DISCORD_GUILD_ID: '111222333444555666'
      DISCORD_DEV_CHANNEL_ALLOWED_LIST: '222333444555666777,333444555666777888'
    defaults:
      run:
        working-directory: ./packages/dev-team-bot

    steps:
      - name: Copy repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install npm dependencies
        run: yarn install

      - name: Lint code
        run: yarn run lint

      - name: Run tests
        run: yarn run test
